import { StudentProfile } from '../../students/entities/student-profile.entity';

export class StudentNote {
    id: string;
    student_id: string;
    student?: StudentProfile;
    topic: string;
    content: string; // Markdown generated by AI
    created_at: Date;
}
